name: Update README Trophy

on:
  schedule:
    - cron: "0 3 * * *"  # يتحدث تلقائياً كل يوم الساعة 3 صباحاً
  workflow_dispatch:     # هذه الخلطة السحرية عشان تقدر تشغله يدوياً

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Create images directory
        run: mkdir -p images

      - name: Generate trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: ${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}
          file: images/trophy.svg
          theme: algolia
          max-rows: 1

      - name: Commit trophy
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add images/trophy.svg
          git commit -m "Update trophy image" || exit 0
          git push
